// Code generated by mockery v2.29.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HTTPBodyDecoder is an autogenerated mock type for the HTTPBodyDecoder type
type HTTPBodyDecoder struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *HTTPBodyDecoder) Execute(_a0 []byte) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewHTTPBodyDecoder interface {
	mock.TestingT
	Cleanup(func())
}

// NewHTTPBodyDecoder creates a new instance of HTTPBodyDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHTTPBodyDecoder(t mockConstructorTestingTNewHTTPBodyDecoder) *HTTPBodyDecoder {
	mock := &HTTPBodyDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
