// Code generated by mockery v2.29.0. DO NOT EDIT.

package mocks

import (
	logger "cypt/internal/logger/entity"

	mock "github.com/stretchr/testify/mock"
)

// LogRepository is an autogenerated mock type for the LogRepository type
type LogRepository struct {
	mock.Mock
}

// WriteAccessLog provides a mock function with given fields: log
func (_m *LogRepository) WriteAccessLog(log *logger.AccessLog) {
	_m.Called(log)
}

// WriteErrorLog provides a mock function with given fields: log
func (_m *LogRepository) WriteErrorLog(log *logger.ErrorLog) {
	_m.Called(log)
}

// WriteHTTPRequestLog provides a mock function with given fields: log
func (_m *LogRepository) WriteHTTPRequestLog(log *logger.HTTPRequestLog) {
	_m.Called(log)
}

// WritePostLog provides a mock function with given fields: log
func (_m *LogRepository) WritePostLog(log *logger.PostLog) {
	_m.Called(log)
}

type mockConstructorTestingTNewLogRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogRepository creates a new instance of LogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogRepository(t mockConstructorTestingTNewLogRepository) *LogRepository {
	mock := &LogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
