// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDRepository is an autogenerated mock type for the IDRepository type
type IDRepository struct {
	mock.Mock
}

// Incr provides a mock function with given fields: _a0
func (_m *IDRepository) Incr(_a0 int) (int64, error) {
	ret := _m.Called(_a0)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int64, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int) int64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDRepository creates a new instance of IDRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDRepository {
	mock := &IDRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
