// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: internal/user/adapter/grpc/protobuffer/user.proto

package protobuffer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RegisterUserInput) Reset() {
	*x = RegisterUserInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterUserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserInput) ProtoMessage() {}

func (x *RegisterUserInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserInput.ProtoReflect.Descriptor instead.
func (*RegisterUserInput) Descriptor() ([]byte, []int) {
	return file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserInput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterUserOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string                     `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Ret    *RegisterUserUseCaseOutput `protobuf:"bytes,2,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *RegisterUserOutput) Reset() {
	*x = RegisterUserOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterUserOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserOutput) ProtoMessage() {}

func (x *RegisterUserOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserOutput.ProtoReflect.Descriptor instead.
func (*RegisterUserOutput) Descriptor() ([]byte, []int) {
	return file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserOutput) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RegisterUserOutput) GetRet() *RegisterUserUseCaseOutput {
	if x != nil {
		return x.Ret
	}
	return nil
}

type RegisterUserUseCaseOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserID   int64  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *RegisterUserUseCaseOutput) Reset() {
	*x = RegisterUserUseCaseOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterUserUseCaseOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserUseCaseOutput) ProtoMessage() {}

func (x *RegisterUserUseCaseOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserUseCaseOutput.ProtoReflect.Descriptor instead.
func (*RegisterUserUseCaseOutput) Descriptor() ([]byte, []int) {
	return file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUserUseCaseOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterUserUseCaseOutput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserUseCaseOutput) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

var File_internal_user_adapter_grpc_protobuffer_user_proto protoreflect.FileDescriptor

var file_internal_user_adapter_grpc_protobuffer_user_proto_rawDesc = []byte{
	0x0a, 0x31, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x22, 0x4b, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x66, 0x0a,
	0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x03, 0x72,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x55, 0x73, 0x65, 0x43, 0x61, 0x73, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x22, 0x5f, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x55, 0x73, 0x65, 0x43, 0x61, 0x73, 0x65, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x32, 0x59, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x51,
	0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22,
	0x00, 0x42, 0x2a, 0x5a, 0x28, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescOnce sync.Once
	file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescData = file_internal_user_adapter_grpc_protobuffer_user_proto_rawDesc
)

func file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescGZIP() []byte {
	file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescOnce.Do(func() {
		file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescData)
	})
	return file_internal_user_adapter_grpc_protobuffer_user_proto_rawDescData
}

var file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_user_adapter_grpc_protobuffer_user_proto_goTypes = []interface{}{
	(*RegisterUserInput)(nil),         // 0: protobuffer.RegisterUserInput
	(*RegisterUserOutput)(nil),        // 1: protobuffer.RegisterUserOutput
	(*RegisterUserUseCaseOutput)(nil), // 2: protobuffer.RegisterUserUseCaseOutput
}
var file_internal_user_adapter_grpc_protobuffer_user_proto_depIdxs = []int32{
	2, // 0: protobuffer.RegisterUserOutput.ret:type_name -> protobuffer.RegisterUserUseCaseOutput
	0, // 1: protobuffer.User.RegisterUser:input_type -> protobuffer.RegisterUserInput
	1, // 2: protobuffer.User.RegisterUser:output_type -> protobuffer.RegisterUserOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_user_adapter_grpc_protobuffer_user_proto_init() }
func file_internal_user_adapter_grpc_protobuffer_user_proto_init() {
	if File_internal_user_adapter_grpc_protobuffer_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterUserInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterUserOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterUserUseCaseOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_user_adapter_grpc_protobuffer_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_user_adapter_grpc_protobuffer_user_proto_goTypes,
		DependencyIndexes: file_internal_user_adapter_grpc_protobuffer_user_proto_depIdxs,
		MessageInfos:      file_internal_user_adapter_grpc_protobuffer_user_proto_msgTypes,
	}.Build()
	File_internal_user_adapter_grpc_protobuffer_user_proto = out.File
	file_internal_user_adapter_grpc_protobuffer_user_proto_rawDesc = nil
	file_internal_user_adapter_grpc_protobuffer_user_proto_goTypes = nil
	file_internal_user_adapter_grpc_protobuffer_user_proto_depIdxs = nil
}
