// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Input is an autogenerated mock type for the Input type
type Input struct {
	mock.Mock
}

type mockConstructorTestingTNewInput interface {
	mock.TestingT
	Cleanup(func())
}

// NewInput creates a new instance of Input. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInput(t mockConstructorTestingTNewInput) *Input {
	mock := &Input{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
