// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Output is an autogenerated mock type for the Output type
type Output struct {
	mock.Mock
}

type mockConstructorTestingTNewOutput interface {
	mock.TestingT
	Cleanup(func())
}

// NewOutput creates a new instance of Output. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOutput(t mockConstructorTestingTNewOutput) *Output {
	mock := &Output{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
